name: Build iOS App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create iOS Project
        run: |
          cordova platform add ios
          cordova build ios --simulator
          
      - name: Locate and Save IPA File
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-package
          path: platforms/ios/build/emulator/*.app
